repos:

- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
    - id: interrogate
      exclude: ^(setup.py|model_catalogs/tests)
      args: [--config=pyproject.toml]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
      # exclude: ^(libgoods|scripts|CHANGES.txt|README.rst|conda_requirements.txt)
    - id: check-ast
      # exclude: ^(libgoods|scripts|CHANGES.txt|README.rst|conda_requirements.txt)
    - id: debug-statements
      # exclude: ^(libgoods|scripts|CHANGES.txt|README.rst|conda_requirements.txt)
    - id: end-of-file-fixer
      # exclude: ^(libgoods|scripts|CHANGES.txt|README.rst|conda_requirements.txt)
    - id: check-docstring-first
      # exclude: ^(libgoods|scripts|CHANGES.txt|README.rst|conda_requirements.txt)
    - id: check-added-large-files
      # exclude: ^(libgoods|scripts|CHANGES.txt|README.rst|conda_requirements.txt)
    - id: requirements-txt-fixer
      # exclude: ^(libgoods|scripts|CHANGES.txt|README.rst|conda_requirements.txt)
    - id: file-contents-sorter
      files: requirements-dev.txt
      # exclude: ^(libgoods|scripts|CHANGES.txt|README.rst|conda_requirements.txt)

- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      # exclude: ^(libgoods|scripts)  #docs/source/conf.py
      args: [--max-line-length=105] #, --ignore=E203,E501,W503] #, --select=select=C,E,F,W,B,B950]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    additional_dependencies: [toml]
    args: [--project=model_catalogs, --multi-line=3, --lines-after-imports=2, --lines-between-types=1, --trailing-comma, --force-grid-wrap=0, --use-parentheses, --line-width=88]
    # exclude: ^(libgoods|scripts|setup.py)

# - repo: https://github.com/asottile/seed-isort-config
#   rev: v2.2.0
#   hooks:
#     - id: seed-isort-config
#       exclude: ^(libgoods|scripts|setup.py)

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3
    # exclude: ^(libgoods|scripts)

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.770
#   hooks:
#   - id: mypy
#     exclude: docs/source/conf.py
#     args: [--ignore-missing-imports]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
    - id: codespell
      exclude: ^(model_catalogs/notebooks|docs)
      args:
        - --quiet-level=2
