version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

python:
  version: "3.9"
  install:
    - method: pip
      path: ./
      # extra_requirements:
      #   - docs
    # - method: setuptools
    #   path: package

conda:
    environment: docs/environment.yml

sphinx:
  configuration: docs/conf.py
  # fail_on_warning: true
