name: test_env_model_catalogs
channels:
  - conda-forge
dependencies:
  - python=3.7
  ############## These will have to be adjusted to your specific project
  - alphashape
  - dask
  - flake8
  - h5netcdf
  # - intake
  # - intake-xarray
  - numpy
  - pandas
  - pip
  - shapely
  - siphon
  - xarray
  ##############
  - pytest
  - pip:
    - git+https://github.com/intake/intake-xarray.git #@open_mfdataset
    - git+https://github.com/intake/intake.git
    - codecov
    - pytest-cov
    - coverage[toml]
