name: test_env_model_catalogs
channels:
  - conda-forge
dependencies:
  - python=3.9
  ############## These will have to be adjusted to your specific project
  - alphashape
  - appdirs
  - cf_xarray
  - dask
  # - extract_model>=0.8.0
  - flake8
  - h5netcdf
  # - intake
  # - intake-xarray
  # - netcdf4
  - numpy
  # - openssl<3.0  # NOMADS server for RTOFS doesn't work with openssl 3.0
  - pandas
  - pip
  - shapely
  - xarray
  ##############
  - pytest
  - pip:
      # intake-xarray version on 2022-07-28 which has fixes for using non-standard engine
    - git+https://github.com/intake/intake-xarray.git@f8368225d6957e5fb0a4b2f24f0b0be28b42a5ea
    - git+https://github.com/intake/intake.git
    - datetimerange
    - codecov
    - pytest-cov
    - coverage[toml]
    - siphon  # can get from conda-forge but isn't recognized
