name: model_catalogs
channels:
  - conda-forge
dependencies:
  - pytest
  - alphashape
  - cf_xarray>=0.6
  - dask
  - erddapy
  - flake8
  - h5netcdf
  # - intake
  # - intake-xarray
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyproj
  - shapely
  - siphon
  - xarray
  - pip:  # install from github to get recent PRs I contributed
    - git+https://github.com/intake/intake-xarray.git #@open_mfdataset
    - git+https://github.com/intake/intake.git
    # - intake-nested-yaml-catalog
