name: test-env-model-catalogs
channels:
  - conda-forge
dependencies:
  - python=3.8
  ############## These will have to be adjusted to your specific project
  - alphashape
  - appdirs
  - cf_xarray
  - dask
  - datetimerange
  - extract_model
  - flake8
  - intake
  - intake-xarray
  - netcdf4
  - numpy
  # - openssl<3.0  # NOMADS server for RTOFS doesn't work with openssl 3.0
  - pandas
  - pip
  - requests
  - shapely
  - siphon
  - xarray
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
